import type { Metadata } from 'next'
import { Itim } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { cn } from '@/lib/utils'
import { TooltipProvider } from '@/components/ui/tooltip'
import ClientProvider from '@/hooks/client-provider'
import { WalletProvider } from '@/hooks/wallet-provider';

const itim = Itim({
  weight: '400',
  subsets: ['latin', 'thai'],
  variable: '--font-itim',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en" className={cn('h-full', 'antialiased', itim.variable)}>
      <body className="min-h-full flex flex-col">
        <ClientProvider>
          <SessionProvider
            session={session}
            refetchInterval={0}
            refetchOnWindowFocus={false}
          >
            <WalletProvider>
              <TooltipProvider>{children}</TooltipProvider>
            </WalletProvider>
          </SessionProvider>
        </ClientProvider>
      </body>
    </html>
  )
}
